### ISSUE TITLE
Change "value" to "biomass per tow" in the map legend

### ISSUE THREAD

**Issue by mstuart1** [pinskylab/OceanAdapt#103]
Hi,

The color represents biomass per tow. If it doesn’t say that somewhere on the map, we’ll add it to the list of updates to make! (cc’ing Michelle to note that).

Regards,
Malin

On Wed 9. Oct 2019 at 02:57, wrote:
Hi Malin - 
Could you tell me what the 'Value' label means on the OceanAdapt maps?  I use the images in talks promoting OceanAdapt and shifting species distributions, and in case someone notices and asks I want to at least be able to give them a very basic answer.    
Thanks!

**Comment by mpinsky** [comment]
Note that the historical maps currently save "Value" in the legend, while the future projection maps say "Relative abundance." Both should be changed to say "Biomass per tow"

**Comment by ljmarxen** [comment]
I have an email from 4/27/18 where we made the decision to use Relative Abundance on the future maps rather than biomass per tow due to the fact that we are using logged values and we needed to suppress some data points that ended up having negative values.  So we don't actually have "biomass per tow" for those maps.  I'm not sure why the legend label changed on the historical maps, but we'll check it out and regenerate the maps as necessary.

**Comment by mpinsky** [comment]
Thanks. This is an update to our design based on the feedback we've received from users in the last year, not a mistake that any of us made. Users would find it easier to understand "Biomass per tow" than "Relative abundance" or "Value." We still don't want to put numbers on the legend, however, and we do still want to leave the values as "High" and "Low."
