### ISSUE TITLE
be careful with left_join() for Maritimes adding extra rows for some species

### ISSUE THREAD

**Issue by zoekitchel** [pinskylab/OceanAdapt#152]
The species list for the maritimes has duplicates for some species because they are caught in multiple seasons. 

In linke 2042 in compile.R, check to make sure this step doesn't multiply rows of 'mar' data frame. 

`mar <- left_join(mar, mar_info, by = "haulid")
mar <- left_join(mar, mar_spp, by = "SPEC")
mar$region <- "Maritimes"`

**Comment by mpinsky** [comment]
@mikeallen-eco  and @zoekitchel , was this addressed in the latest updates, or is it still open?

**Comment by mikeallen-eco** [comment]
I'm not sure. I can look into it.

**Comment by mikeallen-eco** [comment]
The problem seems to be that mar_spp (a lookup table for species name info) has duplicates. It has 1737 rows while distinct(mar_spp) only has 880. So the following command produces duplicates: 
```
mar <- left_join(mar, mar_spp, by = "SPEC")
```
It increases mar from ~488000 rows to ~ 1.8M. I'm not sure what the downstream consequences of this are yet. I think inserting the following before the offending line would fix it, but I'll discuss with @df511 first just to make sure it won't negatively affect downstream:
```
mar_spp <- mar_spp %>% distinct()
```

**Comment by mikeallen-eco** [comment]
This issue was resolved by adding 
```%>% distinct()```
to the code creating the mar_spp object. It resulted in reductions to the estimated catch mass (wtcpue) for the Maritimes region in the final data file.
